package models

type Bhangudatas struct {
	Id int `json:"id"`
	TrackId int `json:"track_id"`
	CustomerName string `json:"customer_name,omitempty"`
	Date string `json:"date,omitempty"`
	Datetimestamp string `json:"datetimestamp"`
	Myob string `json:"myob,omitempty"`
	Installer string `json:"installer,omitempty"`
	AInstallerId int `json:"a_installer_id,omitempty"`
	Address string `json:"address,omitempty"`
	PoFile string `json:"po_file"`
	Po string `json:"po"`
	Subtotal string `json:"subtotal"`
	Qty float64 `json:"qty,omitempty"`
	WallWrap float64 `json:"wall_wrap"`
	WallBats float64 `json:"wall_bats"`
	WallBatsR27 int `json:"wall_bats_r2_7"`
	Celling float64 `json:"celling"`
	StringCelling float64 `json:"string_celling"`
	R50 int `json:"r5_0"`
	Dishing int `json:"dishing"`
	Cutting float64 `json:"cutting"`
	Fireseal int `json:"fireseal"`
	Fixup int `json:"fixup"`
	WindowTape int `json:"window_tape"`
	Tape int `json:"tape"`
	DampCourse int `json:"damp_course"`
	Infill int `json:"infill"`
	EmPrice float64 `json:"em_price"`
	Productcode string `json:"productcode"`
	Description string `json:"description,omitempty"`
	Notes string `json:"notes,omitempty"`
	ScopeOfWork string `json:"scope_of_work,omitempty"`
	UnitPrice string `json:"unit_price"`
	UnitPriceGst string `json:"unit_price_gst"`
	Delivery string `json:"delivery,omitempty"`
	FletcherPo string `json:"fletcher_po,omitempty"`
	Comments string `json:"comments,omitempty"`
	Pid int `json:"pid"`
	Status string `json:"status"`
	InstallerNote string `json:"installer_note"`
	AdminNote string `json:"admin_note"`
	AdminComment string `json:"admin_comment"`
	InvoiceReady int `json:"invoice_ready"`
	JsaLink string `json:"jsa_link"`
	AInstaller string `json:"a_installer,omitempty"`
	JobTimestamp int `json:"job_timestamp"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	NeedInfill string `json:"need_infill"`
	NeedLintel string `json:"need_lintel"`
}